package jp.co.nttdmse.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import jp.co.nttdmse.domain.entity.EmployeeInfo;
import jp.co.nttdmse.domain.entity.EmployeeInfoExample;

@Component
@Mapper
public interface EmployeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    long countByExample(EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    int deleteByExample(EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    int deleteByPrimaryKey(Integer manno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    int insert(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    int insertSelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    List<EmployeeInfo> selectByExample(EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    EmployeeInfo selectByPrimaryKey(Integer manno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    int updateByExampleSelective(@Param("record") EmployeeInfo record, @Param("example") EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    int updateByExample(@Param("record") EmployeeInfo record, @Param("example") EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    int updateByPrimaryKeySelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    int updateByPrimaryKey(EmployeeInfo record);
}