package jp.co.nttdmse.domain.entity;

import java.util.Date;

public class EmployeeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.manno
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    private Integer manno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.name
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.join_date
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    private Date joinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.sex
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.enrollment_type
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    private String enrollmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.time_saving
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    private Boolean timeSaving;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.manno
     *
     * @return the value of employee_info.manno
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public Integer getManno() {
        return manno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.manno
     *
     * @param manno the value for employee_info.manno
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public void setManno(Integer manno) {
        this.manno = manno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.name
     *
     * @return the value of employee_info.name
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.name
     *
     * @param name the value for employee_info.name
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.join_date
     *
     * @return the value of employee_info.join_date
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.join_date
     *
     * @param joinDate the value for employee_info.join_date
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.sex
     *
     * @return the value of employee_info.sex
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.sex
     *
     * @param sex the value for employee_info.sex
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.enrollment_type
     *
     * @return the value of employee_info.enrollment_type
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public String getEnrollmentType() {
        return enrollmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.enrollment_type
     *
     * @param enrollmentType the value for employee_info.enrollment_type
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public void setEnrollmentType(String enrollmentType) {
        this.enrollmentType = enrollmentType == null ? null : enrollmentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.time_saving
     *
     * @return the value of employee_info.time_saving
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public Boolean getTimeSaving() {
        return timeSaving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.time_saving
     *
     * @param timeSaving the value for employee_info.time_saving
     *
     * @mbg.generated Tue Jan 14 11:04:46 JST 2020
     */
    public void setTimeSaving(Boolean timeSaving) {
        this.timeSaving = timeSaving;
    }
}